### ISSUE TITLE
build version stop working after update

### ISSUE THREAD

**Issue by scottiesan** [jasonjmcghee/plock#11]
I'm having issues with the build version since the latest update, but the dev version is working fine for me. Please don't include any additional information, just focus on this problem.

it doesn't seem to be consuming the context.

**Comment by jasonjmcghee** [comment]
Can you try getting the latest version, removing plock from accessibility settings and input monitoring and rebuilding / relaunching?

**Comment by scottiesan** [comment]
Seems like a permission issue.  I fixed this by removing and re-adding plock in System settings.  It now consumes the context, but nothing comes out.   Running the command a few times kills/crashes  plock.  This is with the latest version.

**Comment by jasonjmcghee** [comment]
What a terrible experience- I’m really sorry to hear that.

a workaround you can try is launching the binary with the terminal

**Comment by scottiesan** [comment]
Thank for the quick reply!  I really like this project and the idea.  By the way is this the correct format to use openai model?

{
  "environment": {},
  "ollama": {
    "enabled": false,
    "ollama_model": "openhermes2.5-mistral"
  },
  "model": {
    "enabled": true,
    "model": "gpt-3.5-turbo-1106",
    "OPENAI_API"="sk-xxx"
  },
  "custom_commands": {
    "index": 0,
    "custom_commands": [
      {
        "name": "gpt",
        "command": [
          "bash",
          "/path/to/gpt.sh"
        ]
      }
    ]
  },

Again, Thanks!

**Comment by jasonjmcghee** [comment]
You’ll have to forgive me- i had some larger aspirations and had to reimplement settings. I put an example that includes openai for both chat and dalle. The example is in the “settings” section of the readme and the example scripts are in the “scripts” folder

**Comment by scottiesan** [comment]
ok... i see it.  Is in the settings path to scrip and add the scripts in there.... Thanks!

**Comment by jasonjmcghee** [comment]
Let me know if you have no clue how to use settings… i know it’s not super straight forward.

take a look at the shortcut keys. A “trigger” can be started with a shortcut. That points to a process (by an 0-index) and a prompt (by a 0-index) to the lists defined in the processes and prompts fields.

a process is either “ollama” or a command (shell on mac). You can use that to call your script.

prompts can use one of the two built in variables $CLIPBOARD and $SELECTION, or any others you define using set_env_var trigger.

next_steps defines what happens to the output, which can be written to the screen (streaming or all at once ), saved to a variable, and/or kick off another trigger.

**Comment by scottiesan** [comment]
Did not work with OpenAI model as well.  Seems to be crashing for me.  This is also happening when I use the load setting from system icon menu.  Alos  same issue with both of my mac running 14.2.1 (23C71).

**Comment by jasonjmcghee** [comment]
Sounds like the settings file is invalid. I’ll add better error handling to try to display why it failed. Sorry about that

**Comment by scottiesan** [comment]
Possibly.  got it working on one of my Mac after uninstalling and reinstalling everything. notice the setting file was a little different on the two mac.  Possibly the new install didn't overwrite the old settings and cause some issue.

**Comment by jasonjmcghee** [comment]
Yes, it does _not_ override - didn't want the user to lose settings. Maybe I should move it to like `settings.backup.json` and create the new one? What would make sense to you?

Ideally it would migrate...

**Comment by jasonjmcghee** [comment]
I'm thinking this is resolved. please re-open and correct me if that's not true. apologies for the friction of new settings!
