### ISSUE TITLE
Problems running on arch Linux

### ISSUE THREAD

**Issue by luandro** [jasonjmcghee/plock#16]
First, congrats, this is a really awesome and useful project.
I'm trying to run this on a Manjaro Linux. When running `npm run tauri dev` in the very end I get this error:
```
   Compiling webkit2gtk v0.18.2
warning: unused import: `InputResult`
  --> src/main.rs:10:31
   |
10 | use enigo::{Direction, Enigo, InputResult, Key, Keyboard};
   |                               ^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: use of deprecated function `base64::decode`: Use Engine::decode
 --> src/main.rs:9:13
  |
9 | use base64::decode;
  |             ^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated function `base64::decode`: Use Engine::decode
   --> src/main.rs:411:50
    |
411 | ...                   let image_data = decode(&whole_output.trim())
    |                                        ^^^^^^

error: linking with `cc` failed: exit status: 1`
warning: `plock` (bin "plock") generated 3 warnings
error: could not compile `plock` (bin "plock") due to previous error; 3 warnings emitted
```

Seems to be related to https://github.com/tauri-apps/tauri/issues/1543, but their solution of deleting `src-tauri/target/debug` didn´t  do anything. Any tips?

**Comment by jasonjmcghee** [comment]
The warnings are effectively lint- nbd.

The key is the issue you linked to- failing to link with “cc”. I’ve seen this myself occasionally and fixed it by deleting target entirely.

That being said, it might be a red herring in your case.

Let me just say, I have never used arch Linux.

I see two avenues
- try to debug the issue, use verbose logging etc.
- we could try making a build without tauri
- 

Could you try going into src-tauri and running cargo directly?

**Comment by luandro** [comment]
Thanks for the response! 

Seems like I was ignoring an error at the end, which was basically telling me that I didn't have `xdotool` installed. And now I see you've linked to another repo that does say it's necessary to install it, so it's really my bad for not reading the README properly.

It's working perfectly with tray and everything. Thanks for this!

**Comment by jasonjmcghee** [comment]
Oh fantastic news! Feel free to open a pr suggesting how you would have written it such that it would have been clearer!
