### ISSUE TITLE
settings.json file is missing

### ISSUE THREAD

**Issue by Nicholas0350** [jasonjmcghee/plock#25]
Have i missed something but settings.json file missing from repo

**Comment by jasonjmcghee** [comment]
It gets automatically created. If you click on the tray icon you'll see where it's stored on your system.

I also put an example in the readme.

**Comment by jasonjmcghee** [comment]
I also talk about where it is in the readme, but checking your tray icon is the source of truth.

I'll close for now, but happy to reopen!
