### ISSUE TITLE
exit when hit cmd+shift+/

### ISSUE THREAD

**Issue by happy15** [jasonjmcghee/plock#27]
Everything went well until today. When I hit cmd+shif+/, plock exits without any crash popup or anything.

What may go wrong or anywhere I can see error logs? 

Thanks for the amazing idea and I used it everyday.

**Comment by jasonjmcghee** [comment]
Sorry you had that happen and I'm glad you've found utility in it!

If you're on Mac, you might be able to see via System Logs.

But short answer is, I haven't done a logging solution. That would be a fantastic feature / PR!

**Comment by happy15** [comment]
It's wired and It worked today ... Really don't know what changed.

Close for now and will report with more info next time if happen again.

Thanks for the response.
