### ISSUE TITLE
Application is crashing - logs?

### ISSUE THREAD

**Issue by keviddles** [jasonjmcghee/plock#8]
Things were briefly running great, but I created a custom settings file, and must have broken something. The Plock app crashes upon invocation.

Is there a place where error logs are written, so that I can inspect why it's crashing?

(I'm seeing the crash even with an empty settings file now).

**Comment by keviddles** [comment]
Aha - looks like `ollama` had a pending update. Restarted and things seem to be working again.

The question still stands though - is there anywhere that Plock writes logs to for future issues?

**Comment by nuaimat** [comment]
if you run it from command line terminal (on mac os):
- ```cd /Applications/plock.app/Contents/MacOS```
- ```./plock```
it will show you the stdout/stderror on the terminal

**Comment by jasonjmcghee** [comment]
Apologies for this- yeah right now it just panics when it runs into an issue, but should (hopefully) tell you why it crashed if you run via terminal. Or you can likely go through the [Mac Console](https://support.apple.com/guide/console/find-log-messages-and-activities-cnslbf30b61a/mac) if you're on a Mac

**Comment by keviddles** [comment]
Ah perfect! I'll run it via terminal. Thanks!
