### ISSUE TITLE
Shortcuts are ignored except when running from command line

### ISSUE THREAD

**Issue by nuaimat** [jasonjmcghee/plock#9]
Hello, 

Thank you so much for this amazing code, 
I am on an m1 mac, running macOs sonoma 14.2.1
i faced two issues i will focus on the first issue here: 

installed the plock binaries, and the same issue below appeared, then uninstall the binaries and checked out the code and compile it locally producing the dmg file, when it opens i dragged dropped the plock binary into the applications folder shortcut 
- opening the plock app from the applications folder i can see the icon shows up on the status bar. 
- ollama icon is also showing there (running) 
the issue: selecting any text (inside a text editor) then holding `cmd+shift+.`  or `cmd+shift+/` does nothing 
while opening plock app via terminal:
`cd /Applications/plock.app/Contents/MacOS` 
then `./plock` seems to work and the shortcuts above works fine. 

command line output:
```2024-01-23 19:05:59.988 plock[13855:245451] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
tried to trigger
preparing to copy text...
Context: tell me a joke
tried to trigger```

I am happy to provide any other details required

**Comment by jasonjmcghee** [comment]
I rewrote a bunch of stuff. Can you try removing accessibility permissions (input monitoring etc) from plock and getting latest and regranting it?

**Comment by nuaimat** [comment]
yup works for me now. thanks.
